import pandas as pd
dataFrame_baixado = pd.read_csv(
        r'C:\lotoFacilLast100\dados\LOTOFACIL.csv', sep=';')
######################################################################################################################
OcorrenciaB1 = dataFrame_baixado["B1"].value_counts()
OcorrenciaB2 = dataFrame_baixado["B2"].value_counts()
OcorrenciaB3 = dataFrame_baixado["B3"].value_counts()
OcorrenciaB4 = dataFrame_baixado["B4"].value_counts()
OcorrenciaB5 = dataFrame_baixado["B5"].value_counts()
OcorrenciaB6 = dataFrame_baixado["B6"].value_counts()
OcorrenciaB7 = dataFrame_baixado["B7"].value_counts()
OcorrenciaB8 = dataFrame_baixado["B8"].value_counts()
OcorrenciaB9 = dataFrame_baixado["B9"].value_counts()
OcorrenciaB10 = dataFrame_baixado["B10"].value_counts()
OcorrenciaB11 = dataFrame_baixado["B11"].value_counts()
OcorrenciaB12 = dataFrame_baixado["B12"].value_counts()
OcorrenciaB13 = dataFrame_baixado["B13"].value_counts()
OcorrenciaB14 = dataFrame_baixado["B14"].value_counts()
OcorrenciaB15 = dataFrame_baixado["B15"].value_counts()
######################################################################################################################
OcorrenciaB1.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB1.csv', sep=';')
OcorrenciaB2.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB2.csv', sep=';')
OcorrenciaB3.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB3.csv', sep=';')
OcorrenciaB4.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB4.csv', sep=';')
OcorrenciaB5.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB5.csv', sep=';')
OcorrenciaB6.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB6.csv', sep=';')
OcorrenciaB7.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB7.csv', sep=';')
OcorrenciaB8.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB8.csv', sep=';')
OcorrenciaB9.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB9.csv', sep=';')
OcorrenciaB10.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB10.csv', sep=';')
OcorrenciaB11.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB11.csv', sep=';')
OcorrenciaB12.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB12.csv', sep=';')
OcorrenciaB13.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB13.csv', sep=';')
OcorrenciaB14.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB14.csv', sep=';')
OcorrenciaB15.to_csv(r'C:\lotoFacilLast100\dados\OcorrenciaB15.csv', sep=';')
######################################################################################################################
